server:
  port: 8081
  run_mode: debug
  logpath: /Users/finup/GoglandProjects/awesomeProject/src/harbor_tools
  logname: harborapi.log

harbor:
  addr: https://xxx.finupgroup.com
  user: admin
  password: xxxx

target:
  addr: https://harbor-target.com
  user: admin
  password: Harbortest12345

db:
  name: harbor_tools
  host: 127.0.0.1
  user: richie
  password: zrqzrq
  port: 5432

harbordb:
  name: registry
  host: 127.0.0.1
  user: harbor
  password: 
  port: 5432
