// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"harbor-tools/harbor-tools/config"
	"harbor-tools/harbor-tools/server"
)

// Injectors from wire.go:

func InitServer(configPath string) (func(), error) {
	configConfig, err := config.NewGlobalConfig(configPath)
	if err != nil {
		return nil, err
	}
	v := server.NewServer(configConfig)
	return v, nil
}
